### PR TITLE
upgraded mediainfo to v20.09 to fix segfault on some video

### PR DESCRIPTION
**Pull request by calvinhp**
*Issue #, if available:* N/A

*Description of changes:* Compiled and upgraded media info to v20.09. Built on Amazon Linux 

```
$ uname -ar
Linux ip-172-30-4-217.ec2.internal 4.14.193-149.317.amzn2.x86_64 #1 SMP Thu Sep 3 19:04:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tomnight** [comment]
Thanks for the feedback we will look to add this to the next release.

**Comment by tomnight** [comment]
@calvinhp 
Any chance you could post a brief note on the steps you took to compile mediinfo?

**Comment by calvinhp** [comment]
I followed the instructions from this blog post

https://aws.amazon.com/blogs/compute/extracting-video-metadata-using-lambda-and-mediainfo/

I just changed the download of mediainfo to grab the latest stable release.

**Comment by morjoan** [comment]
Version 5.2.0 of solution is now using MediaInfo v20.09.

**Pull request closed without merging**
